name: Build with webpack

on:
  push:
    branches:
      - secure-env-setup
  pull_request:
    branches:
      - secure-env-setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Install webpack-cli globally
      run: npm install -g webpack-cli

    - name: Build project
      run: npx webpack-cli
